nightscout:
  build: /root/rpi-nightscout/
  environment:
    MONGO_CONNECTION: mongodb://mongo:27017/nightscout
    API_SECRET: nightscout2000
    ENABLE: rawbg bridge
    BRIDGE_USER_NAME: username
    BRIDGE_PASSWORD: password
    BG_HIGH: 220
    BG_LOW: 60
    BG_TARGET_TOP: 180
    BG_TARGET_BOTTOM: 80
    SSL_KEY: /var/opt/ssl/server.key
    SSL_CERT: /var/opt/ssl/serverchain.crt
#    SSL_CA: /var/opt/ssl/cachain.crt
  ports:
    - "1337:1337"
  links:
    - mongo
  volumes:
    - /home/pi/docker/rpi-nightscout:/var/opt/ssl/:ro
  restart: always
mongo:
  image: dhermanns/rpi-mongo:2.6.4
  command: "/opt/mongodb/bin/mongod"
  restart: always
